name: 'Dependency Detection'
description: 'Detects new dependencies added in pull requests'
author: 'Your Name'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'